- name: Getting Redis Repo
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/{{Component}}.repo
  
- name: Intalling {{Component}}
  ansible.builtin.yum:
    name: redis-6.2.7
    state: present

- name: updating {{Component}} config
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/{{Component}}.conf
    - /etc/{{Component}}/{{Component}}.conf
    

- name: Starting redis
  ansible.builtin.service:
    name: "{{Component}}"
    state: started 
    enabled: yes

- name: Setup hostname and disable auto shut down 
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname 
