- name: Setup MongoDB repository
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/{{Component}}.repo

- name: Intalling MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: present

- name: updating mongodb config
  ansible.builtin.replace:
    path: /etc/{{Component}}.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting mongodb
  ansible.builtin.service:
    name: mongod
    state: started 
    enabled: yes

- name: download and extract
  ansible.builtin.include_role:
    name: common
    tasks_from: download_extract

- name: Loading catalogue & user schema 
  community.mongodb.mongodb_shell: 
    file: "/tmp/{{Component}}-main/{{item}}.js"
    idempotent: yes
  loop: 
    - catalogue
    - users


    