- name: demo print
  hosts: all
  vars: 
    URL: google.co.in
  tasks: 
    - name: this is from play1
      ansible.builtin.debug: 
        msg: This is my URL {{URL}}

  vars:
      URL: Yahoo.co.in  
    - name: this is from play2
      ansible.builtin.debug: 
        msg: This is my new URL {{URL}}