- name: Configure the yum repository
  ansible.builtin.shell:  curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -

- name: Install nodeJs & gcc-c++ 
  ansible.builtin.package:
    name: 
      - nodejs
      - gcc-c++
    state: present

- name: adding user {{Appuser}}
  ansible.builtin.user:
    name: "{{Appuser}}"
    comment: Application user {{Appuser}} 

- name: Clean up of the existing files
  ansible.builtin.file:
    path: /home/{{Appuser}}//{{Component}}/
    state: absent

- name: Donwload and extract the file
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/catalogue/archive/main.zip
    dest: /tmp
    remote_src: yes
    
- name: copy file to appuser 
  ansible.builtin.copy: 
    src: /tmp/{{Component}}-main/
    dest: /home/{{Appuser}}//{{Component}}/
    remote_src: yes
  become_user: "{{Appuser}}"

- name: Npm Install
  community.general.npm:
    path: /home/{{Appuser}}//{{Component}}/
  



