- name: Configure the yum repository
  ansible.builtin.shell:  curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -

- name: Install nodeJs & gcc-c++ 
  ansible.builtin.package:
    name: 
      - nodejs
      - gcc-c++
    state: present
