- name: Clean up of the existing files
  ansible.builtin.file:
    path: /home/{{Appuser}}//{{Component}}/
    state: absent
    ignore_errors: true 

- name: donwload and extract 
  ansible.builtin.include_role:
    name: common
    tasks_from: download_extract 
    
- name: copy file to appuser 
  ansible.builtin.copy: 
    src: /tmp/{{Component}}-main/
    dest: /home/{{Appuser}}//{{Component}}/
    remote_src: yes
  become_user: "{{Appuser}}"
  ignore_errors: true