- name: Configure the yum repository
  ansible.builtin.shell:  curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -

- name: Install nodeJs & gcc-c++ 
  ansible.builtin.package:
    name: 
      - nodejs
      - gcc-c++
    state: present

- name: adding user {{Appuser}}
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user 

- name: clean up, donwload and extract 
  ansible.builtin.include_role:
    name: common
    tasks_from: clean_downextrct 
    
- name: Npm Install
  community.general.npm:
    path: /home/{{Appuser}}//{{Component}}/

- name: updating systemd and starting the service 
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_service 

- name: Generating package 
  ansible.builtin.shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
  become_user: "{{Appuser}}"
  args:
    chgdir: /home/{{Appuser}}//{{Component}}/




  



